=== szaloczy/Y4O4X0_MDBPract/Y4O4X0_0218/Y4O4X0_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="unqualified" 
attributeFormDefault="unqualified">


        <xs:element name="cegek">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="ceg" type="CegTipus" maxOccurs="unbounded"/>
                    <xs:element name="tulajdonos" type="TulajdonosTipus" maxOccurs="unbounded"/>
                    <xs:element name="gyakornok" type="GyakornokTipus" maxOccurs="unbounded"/>
                    <xs:element name="fejleszto" type="FejlesztoTipus" maxOccurs="unbounded"/>
                    <xs:element name="megrendelo" type="megrendeloTipus" maxOccurs="unbounded"/>
                    <xs:element name="projekt" type="projektTipus" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:complexType>

            <!--Primary Keys-->

            <xs:key name="ceg_kulcs">
                <xs:selector xpath="ceg"/>
                <xs:field xpath="@ckod"/>
            </xs:key>

            <xs:key name="tulajdonos_kulcs">
                <xs:selector xpath="tulajdonos"/>
                <xs:field xpath="@tkod"></xs:field>
            </xs:key>

            <xs:key name="gyakornok_kulcs">
                <xs:selector xpath="gyakornok"/>
                <xs:field xpath="@gykod"/>
            </xs:key>

            <xs:key name="fejleszto_kulcs">
                <xs:selector xpath="fejleszto"/>
                <xs:field xpath="@fkod"/>
            </xs:key>

            <xs:key name="megrendelo_kulcs">
                <xs:selector xpath="megrendelo"/>
                <xs:field xpath="@mkod"/>
            </xs:key>

            <!--Foreign Keys-->

            <xs:keyref refer="ceg_kulcs" name="ceg_idegen_kulcs">
                <xs:selector xpath="projekt"/>
                <xs:field xpath="@c_v_p"/>
            </xs:keyref>

            <xs:keyref refer="megrendelo_kulcs" name="megrendelo_idegen_kulcs">
                <xs:selector xpath="projekt"/>
                <xs:field xpath="@m_p"/>
            </xs:keyref>

            <xs:keyref refer="ceg_kulcs" name="ceg_tulajdonos_idegen_kulcs">
                <xs:selector xpath="tulajdonos"/>
                <xs:field xpath="@c_t"/>
            </xs:keyref>

            <xs:keyref refer="ceg_kulcs" name="ceg_gyakornok_idegen_kulcs">
                <xs:selector xpath="gyakornok"/>
                <xs:field xpath="@c_gy"/>
            </xs:keyref>

            <xs:keyref refer="ceg_kulcs" name="ceg_fejleszto_idegen_kulcs">
                <xs:selector xpath="fejleszto"/>
                <xs:field xpath="@c_f"/>
            </xs:keyref>


            <!--1:1-->
            <xs:unique name="egyedi_kulcs_tulajdonos">
                <xs:selector xpath="tulajdonos"/>
                <xs:field xpath="@c_t"/>
            </xs:unique>
        </xs:element>

        <!--Common types-->

        <xs:complexType name="CimTipus">
            <xs:sequence>
                <xs:element name="varos" type="xs:string"/>
                <xs:element name="utca" type="xs:string"/>
                <xs:element name="hazszam" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="GyarkolatTipus">
            <xs:sequence>
                <xs:element name="kezdet" type="xs:date"/>
                <xs:element name="idotartam" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>

        <xs:simpleType name="PrioritasTipus">
            <xs:restriction base="xs:int">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="5"/>
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="OsszegTipus">
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="150000"/>
                <xs:maxInclusive value="30000000"/>
            </xs:restriction>
        </xs:simpleType>

         <xs:simpleType name="FizetesTipus">
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="150000"/>
                <xs:maxInclusive value="2500000"/>
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="EletkorTipus">
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="18"/>
                <xs:maxInclusive value="75"/>
            </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="PrioritastTipus">
            <xs:restriction base="xs:string">
                <xs:enumeration value="Magas"/>
                <xs:enumeration value="Közepes"/>
                <xs:enumeration value="Alacsony"/>
            </xs:restriction>
        </xs:simpleType>

        <!--Domain types-->

        <xs:complexType name="CegTipus">
            <xs:sequence>
                <xs:element name="nev" type="xs:string"/>
                <xs:element name="cim" type="CimTipus"/>
            </xs:sequence>
            <xs:attribute name="ckod" type="xs:int" use="required"/>
        </xs:complexType>

        <xs:complexType name="TulajdonosTipus">
            <xs:sequence>
                <xs:element name="nev" type="xs:string"/>
                <xs:element name="eletkor" type="EletkorTipus"/>
                <xs:element name="vegzettseg" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="tkod" type="xs:int" use="required"/>
            <xs:attribute name="c_t" type="xs:int" use="required"/>
        </xs:complexType>

        <xs:complexType name="GyakornokTipus">
            <xs:sequence>
                <xs:element name="nev" type="xs:string"/>
                <xs:element name="gyakorlat" type="GyarkolatTipus"/>
                <xs:element name="mentor" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="gykod" type="xs:string" use="required"/>
            <xs:attribute name="c_gy" type="xs:string" use="required"/>
        </xs:complexType>

        <xs:complexType name="FejlesztoTipus">
            <xs:sequence>
                <xs:element name="nev" type="xs:string"/>
                <xs:element name="Reszleg" type="xs:string"/>
                <xs:element name="fizetes" type="FizetesTipus"/>
                <xs:element name="vegzettseg" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="fkod" type="xs:string" use="required"/>
            <xs:attribute name="c_f" type="xs:string" use="required"/>
        </xs:complexType>

        <xs:complexType name="megrendeloTipus">
            <xs:sequence>
                <xs:element name="nev" type="xs:string"/>
                <xs:element name="hatartido" type="xs:date"/>
                <xs:element name="cim" type="CimTipus"/>
            </xs:sequence>
            <xs:attribute name="mkod" type="xs:string" use="required"/>
        </xs:complexType>

        <xs:complexType name="projektTipus">
            <xs:sequence>
                <xs:element name="osszeg" type="OsszegTipus"/>
                <xs:element name="hatarido" type="xs:string"/>
                <xs:element name="prioritas" type="PrioritasTipus"/>
            </xs:sequence>
            <xs:attribute name="c_v_p" type="xs:string" use="required"/>
            <xs:attribute name="m_p" type="xs:string" use="required"/>
        </xs:complexType>

</xs:schema>

=== szaloczy/Y4O4X0_MDBPract/Y4O4X0_0225/Y4O4X0_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<cegek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noschemaLocation="Y4O4X0_XMLSchema.xsd">
    <ceg ckod="1">
        <nev>Kiss Pista Kft</nev>
        <cim>
            <varos>Mezőnyárád</varos>
            <utca>Kossuth út</utca>
            <hazszam>23</hazszam>
        </cim>

        <tulajdonos tkod="1">
            <nev>Kiss Pista</nev> 
            <eletkor>45</eletkor>
            <vegzettseg>Villamosmérnök</vegzettseg>
        </tulajdonos>

        <gyakornok gykod="1">
            <nev>Szocló Tamás</nev>
            <gyakorlat gykod="1">
                <kezdet>2022 Szeptember 8</kezdet>
                <idotartam>8 hét</idotartam>
            </gyakorlat>
            <mentor>Tompos József</mentor>
        </gyakornok>

        <fejleszto fkod="1">
            <nev>Tompos József</nev>
            <reszleg>IT</reszleg>
            <vegzettseg>Mérnökinformatikus</vegzettseg>
        </fejleszto>

        <projekt pkod="1" ckod="c1">
            <osszeg>3500000</osszeg>
            <hatarido>2030 január 23</hatarido>
            <prioritas>Magas</prioritas>
        </projekt>

        <megrendelo mkod="1" pkod="1">
            <nev>Szabó Tibor</nev>
            <email>szabo@gmail.com</email>
            <cim>
                <varos>Miskolc</varos>
                <utca>Petőfi utca</utca>
                <hazszam>11</hazszam>
            </cim>
        </megrendelo>
    </ceg>

    <ceg ckod="2">
        <nev>Ütvefuró Bt</nev>
        <cim>
            <varos>Budapest</varos>
            <utca>Petőfi út</utca>
            <hazszam>30</hazszam>
        </cim>

        <tulajdonos tkod="1">
            <nev>Nagy József</nev> 
            <eletkor>55</eletkor>
            <vegzettseg>Bsc Gépjárműmérnök</vegzettseg>
        </tulajdonos>

        <gyakornok gykod="1">
            <nev>Turóczi Mátyás</nev>
            <gyakorlat gykod="1">
                <kezdet>2026 Szeptember 15</kezdet>
                <idotartam>12 hét</idotartam>
            </gyakorlat>
            <mentor>Szatmári Béla</mentor>
        </gyakornok>

        <fejleszto fkod="1">
            <nev>Szatmári Béla</nev>
            <reszleg>IT</reszleg>
            <vegzettseg>Bsc Mérnökinformatikus</vegzettseg>
        </fejleszto>

         <fejleszto fkod="2">
            <nev>Pintér Csaba</nev>
            <reszleg>IT</reszleg>
            <vegzettseg>Bsc Mérnökinformatikus</vegzettseg>
        </fejleszto>

         <fejleszto fkod="3">
            <nev>Látó Jenő</nev>
            <reszleg>IT</reszleg>
            <vegzettseg>Bsc Programtervező informatikus</vegzettseg>
        </fejleszto>

        <projekt pkod="1" ckod="c2">
            <osszeg>2200000</osszeg>
            <hatarido>2030 január 23</hatarido>
            <prioritas>Magas</prioritas>
        </projekt>

        <projekt pkod="2" ckod="c2">
            <osszeg>4500000</osszeg>
            <hatarido>2027 december 23</hatarido>
            <prioritas>közepes</prioritas>
        </projekt>

        <megrendelo mkod="1" pkod="1">
            <nev>Rakaczki Sándor</nev>
            <email>rakacz@gmail.com</email>
            <cim>
                <varos>Sajópetri</varos>
                <utca>Szirma utca</utca>
                <hazszam>5</hazszam>
            </cim>
        </megrendelo>

        <megrendelo mkod="1" pkod="1">
            <nev>Fegyverneki Csaba</nev>
            <email>csaba@gmail.com</email>
            <cim>
                <varos>Budakeszi</varos>
                <utca>Dobó utca</utca>
                <hazszam>15</hazszam>
            </cim>
        </megrendelo>
    </ceg>
</cegek>

=== szaloczy/Y4O4X0_MDBPract/Y4O4X0_0218/Y4O4X0_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<cegek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noschemaLocation="Y4O4X0_XMLSchema.xsd">
    <ceg ckod="1">
        <nev>Kiss Pista Kft</nev>
        <cim>
            <varos>Mezőnyárád</varos>
            <utca>Kossuth út</utca>
            <hazszam>23</hazszam>
        </cim>
        <tulajdonos tkod="1">
            <nev>Kiss Pista</nev> 
            <eletkor>45</eletkor>
            <vegzettseg>Villamosmérnök</vegzettseg>
        </tulajdonos>
        <gyakornok gykod="1">
            <nev>Kiss Tamás</nev>
            <gyakorlat gykod="1">
                <kezdet>2022 Szeptember 8</kezdet>
                <idotartam>8 hét</idotartam>
            </gyakorlat>
            <mentor>Tompos József</mentor>
        </gyakornok>
        <fejleszto fkod="1">
            <nev>Tompos József</nev>
            <reszleg>IT</reszleg>
            <vegzettseg>Mérnökinformatikus</vegzettseg>
        </fejleszto>
        <projekt pkod="1">
            <osszeg>3500000</osszeg>
            <hatarido>2030 január 23</hatarido>
            <prioritas>Magas</prioritas>
        </projekt>
        <megrendelo mkod="1">
            <nev>Szabó Tibor</nev>
            <email>szabo@gmail.com</email>
            <cim>
                <varos>Miskolc</varos>
                <utca>Petőfi utca</utca>
                <hazszam>11</hazszam>
            </cim>
        </megrendelo>
    </ceg>
</cegek>
